version: '3.7'

services:

  php:
    build:
      context: ./docker/swoole
      args:
        SUPERVISOR_CONF: ${DOCKER_SUPERVISOR_CONF}
    container_name: ${DOCKER_APP_NAME}-php
    volumes:
      - ".:/var/www/html"
    expose:
      - 8001
      - 8002
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - kanata-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${DOCKER_APP_NAME}-rabbitmq
    expose:
      - "5672"
      - "15672"
      - "25672"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    networks:
      - kanata-network

networks:
  kanata-network:
    driver: bridge