version: '3.7'

services:

  php:
    build:
      context: ./docker/swoole
    container_name: ${DOCKER_APP_NAME}-php
    volumes:
      - ".:/var/www/html"
    expose:
      - 8001
      - 8002
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      masa-network:
        ipv4_address: ${DOCKER_APP_IP}.0.2

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${DOCKER_APP}-rabbitmq
    expose:
      - "5672"
      - "15672"
      - "25672"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    networks:
      - econoroute-network

networks:
  masa-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_APP_IP}.0.0/16
          gateway: ${DOCKER_APP_IP}.0.1