#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
include_once __DIR__ . '/src/constants.php';
include_once __DIR__ . '/src/helpers.php';

use App\Commands\DebuggerCommand;
use App\Commands\InfoCommand;
use Symfony\Component\Console\Application;
use App\Commands\InitCommand;

$application = new Application();

$application->add(new InitCommand());
$application->add(new InfoCommand());
$application->add(new DebuggerCommand());

$application->run();
