#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Lazer\Classes\Database as Lazer;
use Lazer\Classes\Helpers\Validate;
use Lazer\Classes\LazerException;
use Symfony\Component\Process\Process;


foreach ([
    realpath(__DIR__) . '/data/',
    realpath(__DIR__) . '/../data/',
    realpath(__DIR__) . '/../../data/',
 ] as $file) {
    if (file_exists($file)) {
        define('LAZER_DATA_PATH', $file);
        break;
    } else {
        exit('Error: "data" directory doesn\'t exist!');
    }
}

// -----------------------------------------------------
// prepare json dbs
// -----------------------------------------------------

// plugins
$plugins_table = 'plugins';
try {
    Validate::table($plugins_table)->exists();
} catch (LazerException $e) {
    Lazer::create($plugins_table, [
        'active' => 'boolean',
        'directory_name' => 'string',
        'path' => 'string',
        'name' => 'string',
        'author_name' => 'string',
        'author_email' => 'string',
        'description' => 'string',
    ]);
}

// ws channels
$wschannels_table = 'wschannels';
try {
    Validate::table($wschannels_table)->exists();
} catch (LazerException $e) {
    Lazer::create($wschannels_table, [
        'fd' => 'string',
        'channel' => 'string',
    ]);
}

// ws listeners
$wslisteners_table = 'wslisteners';
try {
    Validate::table($wslisteners_table)->exists();
} catch (LazerException $e) {
    Lazer::create($wslisteners_table, [
        'fd' => 'string',
        'action' => 'string',
    ]);
}

// ws communications
$wscommunications_table = 'wscommunications';
try {
    Validate::table($wscommunications_table)->exists();
} catch (LazerException $e) {
    Lazer::create($wscommunications_table, [
        'action' => 'string',
        'data' => 'string',
    ]);
}